// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCvL_aGl8JDYO-mdlolYuM1Mi8pUHQCFEo",
    authDomain: "msta-pits-dev.firebaseapp.com",
    databaseURL: "https://msta-pits-dev-default-rtdb.firebaseio.com",
    projectId: "msta-pits-dev",
    storageBucket: "msta-pits-dev.firebasestorage.app",
    messagingSenderId: "302427474416",
    appId: "1:302427474416:web:37f174d9f63bcd2b96f535",
    measurementId: "G-5SLTPT801Y",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNJ-P9Mam5svO5yLNQ0FrOjZP7NRJNEA',
    appId: '1:302427474416:android:50ce5be0e84c35b296f535',
    messagingSenderId: '302427474416',
    projectId: 'msta-pits-dev',
  );
}
